format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$nodejs\
$fill\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[username]
style_user = "gray"
format = "[$user]($style) "
disabled = false
show_always = true

[directory]
style = "gray"
read_only = ""
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](bright-black)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "yellow"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"
disabled = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
disabled = true

[git_metrics]
disabled = true

[nodejs]
format = '[\($version\)](cyan) '
disabled = true

# Output the command duration if over 2 seconds
[cmd_duration]
min_time = 2_000
format = "[ $duration ]($style)"
style = "bright-black"